-- Baseline migration: makes Go migrations the authoritative source for
-- the four tables that existed before this project (created originally by
-- ../scryfall/load_scryfall.py and manual canonical_cards work).
--
-- This file uses CREATE TABLE IF NOT EXISTS so it is safe to apply against
-- either a fresh database or one that already has these tables.
--
-- For an existing database that already has these tables:
--   migrate -path ./migrations -database "mysql://..." force 1
-- That marks this migration as applied without re-running it.

CREATE TABLE IF NOT EXISTS sets (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  code            VARCHAR(16)  NOT NULL,
  name            VARCHAR(255) NOT NULL,
  set_type        VARCHAR(64),
  released_at     DATE,
  block_code      VARCHAR(16),
  block           VARCHAR(128),
  parent_set_code VARCHAR(16),
  card_count      INT,
  printed_size    INT,
  digital         TINYINT(1),
  foil_only       TINYINT(1),
  nonfoil_only    TINYINT(1),
  mtgo_code       VARCHAR(16),
  arena_code      VARCHAR(16),
  tcgplayer_id    BIGINT,
  scryfall_uri    VARCHAR(512),
  uri             VARCHAR(512),
  icon_svg_uri    VARCHAR(512),
  search_uri      VARCHAR(512),
  UNIQUE KEY uk_sets_code (code),
  INDEX idx_sets_released_at (released_at),
  INDEX idx_sets_type (set_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cards (
  id                   CHAR(36)     NOT NULL PRIMARY KEY,
  oracle_id            CHAR(36),
  name                 VARCHAR(512) NOT NULL,
  lang                 VARCHAR(8)   NOT NULL,
  layout               VARCHAR(32),
  released_at          DATE,
  set_id               CHAR(36),
  set_code             VARCHAR(16),
  set_name             VARCHAR(255),
  set_type             VARCHAR(64),
  collector_number     VARCHAR(32),
  rarity               VARCHAR(32),
  cmc                  FLOAT,
  mana_cost            VARCHAR(128),
  type_line            VARCHAR(255),
  oracle_text          TEXT,
  power                VARCHAR(16),
  toughness            VARCHAR(16),
  loyalty              VARCHAR(16),
  defense              VARCHAR(16),
  life_modifier        VARCHAR(16),
  hand_modifier        VARCHAR(16),
  edhrec_rank          INT,
  penny_rank           INT,
  artist               VARCHAR(255),
  flavor_text          TEXT,
  flavor_name          VARCHAR(255),
  printed_name         VARCHAR(512),
  printed_text         TEXT,
  printed_type_line    VARCHAR(255),
  border_color         VARCHAR(32),
  frame                VARCHAR(16),
  card_back_id         CHAR(36),
  illustration_id      CHAR(36),
  watermark            VARCHAR(64),
  security_stamp       VARCHAR(32),
  image_status         VARCHAR(32),
  reserved             TINYINT(1),
  reprint              TINYINT(1),
  variation            TINYINT(1),
  variation_of         CHAR(36),
  oversized            TINYINT(1),
  promo                TINYINT(1),
  digital              TINYINT(1),
  full_art             TINYINT(1),
  textless             TINYINT(1),
  booster              TINYINT(1),
  story_spotlight      TINYINT(1),
  highres_image        TINYINT(1),
  content_warning      TINYINT(1),
  foil                 TINYINT(1),
  nonfoil              TINYINT(1),
  arena_id             BIGINT,
  mtgo_id              BIGINT,
  mtgo_foil_id         BIGINT,
  tcgplayer_id         BIGINT,
  tcgplayer_etched_id  BIGINT,
  cardmarket_id        BIGINT,
  uri                  VARCHAR(512),
  scryfall_uri         VARCHAR(512),
  rulings_uri          VARCHAR(512),
  prints_search_uri    VARCHAR(512),
  colors               JSON,
  color_identity       JSON,
  color_indicator      JSON,
  keywords             JSON,
  produced_mana        JSON,
  finishes             JSON,
  games                JSON,
  frame_effects        JSON,
  promo_types          JSON,
  attraction_lights    JSON,
  multiverse_ids       JSON,
  artist_ids           JSON,
  legalities           JSON,
  image_uris           JSON,
  prices               JSON,
  related_uris         JSON,
  purchase_uris        JSON,
  card_faces           JSON,
  all_parts            JSON,
  preview              JSON,
  INDEX idx_cards_oracle_id (oracle_id),
  INDEX idx_cards_set_id (set_id),
  INDEX idx_cards_set_code (set_code),
  INDEX idx_cards_name (name(191)),
  INDEX idx_cards_lang (lang),
  INDEX idx_cards_released_at (released_at),
  INDEX idx_cards_rarity (rarity),
  INDEX idx_cards_tcgplayer_id (tcgplayer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS canonical_cards (
  id                CHAR(36)     NOT NULL,
  oracle_id         CHAR(36)     NOT NULL,
  name              VARCHAR(512) NOT NULL,
  layout            VARCHAR(32),
  released_at       DATE,
  set_id            CHAR(36),
  set_code          VARCHAR(16),
  set_name          VARCHAR(255),
  set_type          VARCHAR(64),
  collector_number  VARCHAR(32),
  rarity            VARCHAR(32),
  cmc               FLOAT,
  mana_cost         VARCHAR(128),
  type_line         VARCHAR(255),
  oracle_text       TEXT,
  power             VARCHAR(16),
  toughness         VARCHAR(16),
  loyalty           VARCHAR(16),
  defense           VARCHAR(16),
  colors            JSON,
  color_identity    JSON,
  color_indicator   JSON,
  keywords          JSON,
  produced_mana     JSON,
  legalities        JSON,
  card_faces        JSON,
  edhrec_rank       INT,
  penny_rank        INT,
  artist            VARCHAR(255),
  flavor_text       TEXT,
  border_color      VARCHAR(32),
  frame             VARCHAR(16),
  illustration_id   CHAR(36),
  image_status      VARCHAR(32),
  image_uris        JSON,
  highres_image     TINYINT(1),
  reserved          TINYINT(1),
  full_art          TINYINT(1),
  booster           TINYINT(1),
  foil              TINYINT(1),
  nonfoil           TINYINT(1),
  tcgplayer_id      BIGINT,
  cardmarket_id     BIGINT,
  mtgo_id           BIGINT,
  scryfall_uri      VARCHAR(512),
  prices            JSON,
  purchase_uris     JSON,
  all_parts         JSON,
  updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                                 ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (oracle_id),
  UNIQUE KEY uq_canonical_card_id (id),
  KEY idx_canonical_name (name(191)),
  KEY idx_canonical_set_code (set_code),
  KEY idx_canonical_set_type (set_type),
  KEY idx_canonical_cmc (cmc),
  KEY idx_canonical_rarity (rarity),
  KEY idx_canonical_tcgplayer_id (tcgplayer_id),
  KEY idx_canonical_edhrec_rank (edhrec_rank),
  KEY idx_canonical_released_at (released_at),
  CONSTRAINT fk_canonical_card_id FOREIGN KEY (id) REFERENCES cards (id)
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS load_meta (
  load_date     VARCHAR(20) NOT NULL PRIMARY KEY,
  cards_loaded  BIGINT,
  sets_loaded   INT,
  loaded_at     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
